### PR TITLE
2018 refactoring

### PR DESCRIPTION
**Pull request by SorenSpicknall**
Removed a bunch of old files, and updated all known copyright dates. I've tested this very thoroughly on my own and verified that each removed file wasn't referenced elsewhere. However, I'd suggest doing some of your own sleuthing to ensure that everything is in order, given the fickle nature of GitHub's search functionality.

### CODE REVIEW

**Comment by vkoves** [comment]
I certainly don't think the In Clouds page and relevant assets should be deleted. I need to transfer that over to my personal site. Otherwise I'm going to need to sit down and really chew through this to make sure nothing's deleted that shouldn't be

**Comment by SorenSpicknall** [comment]
The full commit history, including all versions of the site which included In Clouds, are available to check out from the repository at any time. In the meantime, I **really** don't think it's a good idea to keep that and other old pages up, accessible, and findable through search engines.

**Comment by vkoves** [comment]
Fair enough. I'll reconsider that point.

**Comment by SorenSpicknall** [comment]
@rjaltman, be sure to take a look at whether the Snowshoes pages are all still working.

**Review by rjaltman — APPROVED** [review]
On a high-level, these changes look good. Even pages like 404s seem to be linking correctly, the changes don't negatively impact everything, and this cleans up nicely. That said, the specific resources that are removed here are plenty - I still have to go through them all, but this looks good to go for now...especially given that we're using versioning control and the worst that can happen is we restore old files a/o commits here.

*Edit:* The Snowshoes pages work. I mean, they look awful and don't really work, but they don't work less than before. (We'll get there.)

**Pull request merged**
