### PR TITLE
Added New Members + New Photos

### PR DESCRIPTION
**Pull request by SorenSpicknall**
Added people folders for Jasper and Kyle, and uploaded new photos for each team member in greyscale.

TESTERS: Please check that git properly updated all photos that have shared names with previous files (i.e. each photo from team members besides Jasper and Kyle).

### CODE REVIEW

**Comment by rjaltman** [comment]
Note: This addresses #30.

**Review by rjaltman — CHANGES_REQUESTED** [review]
It looks like Krisztian's photo has not had grayscale applied to it, and since he is still listed on Carpe's project page, this is the only image that is non-grayscale. We should probably just remove the image, but I did want to ask first before turning this into an approval - should we bundle that along with being able to click on a person to go to the about page in a separate PR, or put that change in this one?

**Comment by SorenSpicknall** [comment]
Robert, while we discussed the fact that Krisztian is still on project pages on Sunday, I didn't think about the color difference between the photo versions. Given that there's an upcoming PR that would remove Krisztian, perhaps we should just remove his listing from the project pages in this one as a solution to get this PR approved.

**Comment by vkoves** [comment]
@AcademyInPeril - I'd agree with that thought. Please update this PR and tag me and Robert for re-review when it is complete.

**Comment by SorenSpicknall** [comment]
@vkoves and @rjaltman, it's ready to go!

**Comment by vkoves** [comment]
Overall this looks fine, but I don't like that some of the photos have grey backgrounds, I think the white background (photos Jasper, Kyle, and me) look a lot better

**Comment by vkoves** [comment]
Overall this looks fine, but I don't like that some of the photos have grey backgrounds, I think the white background (photos Jasper, Kyle, and me) look a lot better. The images (despite being black and white) don't strike me as consistent because of this.

image

**Review by vkoves — APPROVED** [review]
Overall good for now, good work!

**Comment by rjaltman** [comment]
Hmmm, I actually do agree with that, @vkoves. If there was a way to alternate between light and dark backgrounds it might be more visually consistent, for example since Soren's photo here also looks fairly stable (good) in terms of contrast. Perhaps he can be moved up the page, and a couple of other images modified? That said, Matt's photo is on a light background as well...so we I think have no choice but to make do with what we have.

**Review by rjaltman — APPROVED** [review]
This is a good update and should be pushed as soon as we can to reflect membership changes, despite the commentary left earlier. Nicely done, @AcademyInPeril!

**Pull request merged**
